# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Account(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, expiry: str=None):  # noqa: E501
        """Account - a model defined in Swagger

        :param id: The id of this Account.  # noqa: E501
        :type id: str
        :param name: The name of this Account.  # noqa: E501
        :type name: str
        :param expiry: The expiry of this Account.  # noqa: E501
        :type expiry: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'expiry': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'expiry': 'expiry'
        }

        self._id = id
        self._name = name
        self._expiry = expiry

    @classmethod
    def from_dict(cls, dikt) -> 'Account':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Account of this Account.  # noqa: E501
        :rtype: Account
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Account.


        :return: The id of this Account.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Account.


        :param id: The id of this Account.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Account.

        Account title that is displayed to a user.  # noqa: E501

        :return: The name of this Account.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Account.

        Account title that is displayed to a user.  # noqa: E501

        :param name: The name of this Account.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def expiry(self) -> str:
        """Gets the expiry of this Account.

        Account expiry date as integer YYYYMMDD  # noqa: E501

        :return: The expiry of this Account.
        :rtype: str
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry: str):
        """Sets the expiry of this Account.

        Account expiry date as integer YYYYMMDD  # noqa: E501

        :param expiry: The expiry of this Account.
        :type expiry: str
        """
        if expiry is None:
            raise ValueError("Invalid value for `expiry`, must not be `None`")  # noqa: E501

        self._expiry = expiry
