# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.statistics import Statistics  # noqa: F401,E501
from swagger_server import util


class InlineResponse2004D(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, stats: List[Statistics]=None):  # noqa: E501
        """InlineResponse2004D - a model defined in Swagger

        :param stats: The stats of this InlineResponse2004D.  # noqa: E501
        :type stats: List[Statistics]
        """
        self.swagger_types = {
            'stats': List[Statistics]
        }

        self.attribute_map = {
            'stats': 'stats'
        }

        self._stats = stats

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004D':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4_d of this InlineResponse2004D.  # noqa: E501
        :rtype: InlineResponse2004D
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stats(self) -> List[Statistics]:
        """Gets the stats of this InlineResponse2004D.


        :return: The stats of this InlineResponse2004D.
        :rtype: List[Statistics]
        """
        return self._stats

    @stats.setter
    def stats(self, stats: List[Statistics]):
        """Sets the stats of this InlineResponse2004D.


        :param stats: The stats of this InlineResponse2004D.
        :type stats: List[Statistics]
        """

        self._stats = stats
