# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2004_d import InlineResponse2004D  # noqa: F401,E501
from swagger_server import util


class InlineResponse2005D(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, league_id: str=None, stats: InlineResponse2004D=None):  # noqa: E501
        """InlineResponse2005D - a model defined in Swagger

        :param league_id: The league_id of this InlineResponse2005D.  # noqa: E501
        :type league_id: str
        :param stats: The stats of this InlineResponse2005D.  # noqa: E501
        :type stats: InlineResponse2004D
        """
        self.swagger_types = {
            'league_id': str,
            'stats': InlineResponse2004D
        }

        self.attribute_map = {
            'league_id': 'leagueId',
            'stats': 'stats'
        }

        self._league_id = league_id
        self._stats = stats

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005D':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5_d of this InlineResponse2005D.  # noqa: E501
        :rtype: InlineResponse2005D
        """
        return util.deserialize_model(dikt, cls)

    @property
    def league_id(self) -> str:
        """Gets the league_id of this InlineResponse2005D.


        :return: The league_id of this InlineResponse2005D.
        :rtype: str
        """
        return self._league_id

    @league_id.setter
    def league_id(self, league_id: str):
        """Sets the league_id of this InlineResponse2005D.


        :param league_id: The league_id of this InlineResponse2005D.
        :type league_id: str
        """

        self._league_id = league_id

    @property
    def stats(self) -> InlineResponse2004D:
        """Gets the stats of this InlineResponse2005D.


        :return: The stats of this InlineResponse2005D.
        :rtype: InlineResponse2004D
        """
        return self._stats

    @stats.setter
    def stats(self, stats: InlineResponse2004D):
        """Sets the stats of this InlineResponse2005D.


        :param stats: The stats of this InlineResponse2005D.
        :type stats: InlineResponse2004D
        """

        self._stats = stats
